# global:
#   scrape_interval: 10s # By default, scrape targets every 10 seconds.
#   evaluation_interval: 10s # Evaluate rules every 10 seconds.

# scrape_configs:
#   - job_name: 'smtm'
#     static_configs:
#     - targets: ["backend:8000"]
#     # - host.docker.internal:8000

global:
  scrape_interval: 10s
  evaluation_interval: 10s

  external_labels:
    monitor: django-monitor

rule_files:
- "django.rules"

scrape_configs:
- job_name: "django"
  static_configs:
  - targets: ["backend:8000"]