# global:
#   scrape_interval: 10s # By default, scrape targets every 10 seconds.
#   evaluation_interval: 10s # Evaluate rules every 10 seconds.

# scrape_configs:
#   - job_name: 'smtm'
#     static_configs:
#     - targets: ["backend:8000"]
#     # - host.docker.internal:8000

global:
  scrape_interval: 10s
  evaluation_interval: 10s

  external_labels:
    monitor: django-monitor

rule_files:
- "django.rules"

scrape_configs:
- job_name: smtm
  scrape_interval: 5s
  static_configs:
  - targets:
    - localhost:9090
    - cadvisor:8080
    - node-exporter:9100
#    - localhost:9100
#    - backend:8000

#scrape_configs:
## 데이터를 스크랩할 위치를 나타내는 scrape_config
#  - job_name: 'backend'
#    metrics_path: '/metrics'
#    static_configs:
#      - targets:
#        - backend:8000
#
#  - job_name: 'cadvisor'
#    scrape_interval: 5s
#    static_configs:
#      - targets:
#        - cadvisor:8080