# Generated by Django 4.1.5 on 2023-01-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='memo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
