name: Deploy CD
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_SSH_HOST }}
          username: ${{ secrets.AWS_SSH_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: ${{ secrets.AWS_SSH_PORT }}
          script: |
            cd docker
            git pull
            docker stop $(docker ps -a -q)
            docker-compose -f docker-compose.prod.yml down 
            docker-compose -f docker-compose.prod.yml up -d --build
            sleep 10s
            docker-compose -f docker-compose.prod.yml exec -T backend python manage.py migrate



